// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Status {
    "currentVersion": string;
    "latestVersion": string;
    "phase": string;
    "automatic": boolean;
    "supported": boolean;
    "releaseURL": string;
    "error": string;
    "lastChecked": string;
}
