// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Agent {
    "name": string;
    "enabled": boolean;
    "exclude": string[] | null;
}

export interface State {
    "step": Step;
    "repositoryUrl": string;
    "authMode": string;
    "userCode"?: string;
    "verificationUri"?: string;
    "message"?: string;
    "agents"?: Agent[] | null;
}

export enum Step {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Welcome = "welcome",
    Repository = "repository",
    Authentication = "authentication",
    Verification = "verification",
    Agents = "agents",
    Ready = "ready",
};
