// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent is one provider shown in the desktop application.
 */
export interface Agent {
    "name": string;
    "enabled": boolean;
    "exclude": string[] | null;
}

/**
 * SettingsInput contains editable desktop settings.
 */
export interface SettingsInput {
    "repositoryUrl": string;
    "intervalMinutes": number;
    "trashGraceDays": number;
    "agents": { [_ in string]?: boolean } | null;
}

/**
 * Snapshot is the current desktop-visible sync state.
 */
export interface Snapshot {
    "configured": boolean;
    "state": string;
    "repositoryUrl": string;
    "intervalMinutes": number;
    "trashGraceDays": number;
    "agents": Agent[] | null;
    "lastSync": string;
    "nextSync": string;
    "pendingActions": number;
    "blockedFiles": number;
    "lastError": string;
}
