// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsService exposes the UI-safe desktop API to generated Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(3233963532);
}

export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(1167946741);
}

export function SaveSettings(input: $models.SettingsInput): $CancellablePromise<void> {
    return $Call.ByID(3861930266, input);
}

export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2631033270);
}

export function TriggerSync(): $CancellablePromise<void> {
    return $Call.ByID(2713968177);
}
